-- AlterTable
ALTER TABLE `User`
  ADD COLUMN `role` VARCHAR(191) NOT NULL DEFAULT 'user',
  ADD COLUMN `isBanned` BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN `bannedAt` DATETIME(3) NULL,
  ADD COLUMN `banReason` TEXT NULL;
